### ISSUE TITLE
NoMethodError with ING-DiBa Import

### ISSUE THREAD

**Issue by peterjeschke** [schurig/ynab-bank-importer#34]
I just added my ING-DiBa account, but received this errormessage:

```
Traceback (most recent call last):
        9: from /usr/app/run.rb:9:in `<main>'
        8: from /usr/app/run.rb:9:in `map'
        7: from /usr/app/run.rb:11:in `block in <main>'
        6: from /usr/app/lib/account.rb:18:in `fetch_transactions'
        5: from /usr/app/lib/dumper/fints.rb:21:in `fetch_transactions'
        4: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/client.rb:19:in `get_sepa_accounts'
        3: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:28:in `sync'
        2: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:28:in `new'
        1: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/segment/hkidn.rb:7:in `initialize'
/usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/helper.rb:4:in `fints_escape': undefined method `gsub' for <myUsername>:Integer (NoMethodError)
```
Note that I redacted my username from the logs. The config, but can't find a mistake.

**Comment by stephanlinke** [comment]
I just set up the docker container last night and the same is happening in my setup with an ING-DiBa account. The config.yml is seemingly correct, though. Also checked the config for any weird characters, no luck :/ Same with a non-docker install.

**Comment by peterjeschke** [comment]
I found the mistake: It's a configuration error (kinda). ING-DiBa usernames only contain digits, so the YAML-parser parses the username as integer, causing a string operation in `ruby_fints` to fail. A temporary fix is to enclose the username in quotes.

**Comment by schurig** [comment]
Awesome @peterjeschke!! Good catch! I just added it to the documentation so that other people don't run into that problem https://github.com/schurig/ynab-bank-importer/wiki/FinTS---HBCI.

@stephanlinke do you mind trying the same and see if it resolves your issue?
